include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
  language:
    strict-casts: false
    strict-inference: false
    strict-raw-types: false
  errors:
    invalid_annotation_target: ignore
    # Keep strict-casts as warnings not errors to avoid red IDE while still linting
    argument_type_not_assignable: warning

linter:
  rules:
    - always_declare_return_types
    - avoid_print
    - avoid_empty_else
    - avoid_relative_lib_imports
    - avoid_returning_null_for_void
    - avoid_type_to_string
    - avoid_web_libraries_in_flutter
    - cancel_subscriptions
    - close_sinks
    - depend_on_referenced_packages
    - directive_ordering
    - file_names
    - hash_and_equals
    - invariant_booleans
    - iterable_contains_unrelated_type
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - prefer_void_to_null
    - sort_child_properties_last
    - test_types_in_equals
    - unnecessary_statements
    - use_key_in_widget_constructors
    - valid_regexps
